// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StashBot;

namespace StashBot.Migrations
{
    [DbContext(typeof(StashBotDbContext))]
    [Migration("20200601171921_Modify_QueueItem_001")]
    partial class Modify_QueueItem_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("StashBot.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDeleteOthers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanFlushQueue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageAuthors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanQueue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("StashBot.Models.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorTelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorTelegramName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorTelegramUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsernameUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Queue");
                });
#pragma warning restore 612, 618
        }
    }
}
